### ISSUE TITLE
Warning Error in Home Assistant Logs

### ISSUE THREAD

**Issue by dcollura83** [cicavey/concord#6]
implicit state_topic is deprecated, add "state_topic":"homeassistant/binary_sensor/concord_zone_1/state" to homeassistant/binary_sensor/concord_zone_1/config discovery message
Connection lost. Reconnecting…

**Comment by cicavey** [comment]
Sorry for the delay! I didn't have notifications turned on for this project and never noticed your issues. I discovered this issue myself as some recent covid projects include learning more HA. I've been mostly using rules in node-red (I find this easier than HA) and treated HA mostly as a dashboard. I never noticed the missing state_topic because my rules in node-red continued to work.
